<a href="https://colab.research.google.com/github/Sneha-rathod123/Session15-Practice/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving popular_shows_dataset.csv to popular_shows_dataset.csv

In [ ]:
filepath="/content/popular_shows_dataset.csv"
df=pd.read_csv(filepath)

In [ ]:
df

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
...,...,...,...,...,...,...
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

In [ ]:
df.head()

              title  year   revenue     imdb_id  tmdb_id  trakt_id
0           Hoppers  2026  29000000  tt26443616  1327819   1085761
1  Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2         undertone  2026   9300000  tt35892608  1480387   1213506
3          Scream 7  2026   8400000  tt27047903  1159559    934134
4              GOAT  2026   4700000  tt27613895  1297842   1057839

In [ ]:
df.tail()

,title,year,revenue,imdb_id,tmdb_id,trakt_id
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

In [ ]:
df.shape

(1000, 6)

In [ ]:
df.columns

Index(['title', 'year', 'revenue', 'imdb_id', 'tmdb_id', 'trakt_id'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1000 non-null   object
 1   year      1000 non-null   int64
 2   revenue   1000 non-null   int64
 3   imdb_id   1000 non-null   object
 4   tmdb_id   1000 non-null   int64
 5   trakt_id  1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

In [ ]:
df.describe()

              year       revenue       tmdb_id      trakt_id
count  1000.000000  1.000000e+03  1.000000e+03  1.000000e+03
mean   2018.800000  7.750000e+06  1.029867e+06  8.375175e+05
std      14.414152  8.705877e+06  5.195836e+05  4.246083e+05
min    1989.000000  1.100000e+06  1.497000e+03  9.910000e+02
25%    2026.000000  1.700000e+06  1.159559e+06  9.341340e+05
50%    2026.000000  3.400000e+06  1.234494e+06  1.000940e+06
75%    2026.000000  9.300000e+06  1.327819e+06  1.085761e+06
max    2026.000000  2.900000e+07  1.480387e+06  1.213506e+06

In [ ]:
df.dtypes

title       object
year         int64
revenue      int64
imdb_id     object
tmdb_id      int64
trakt_id     int64
dtype: object

In [ ]:
df.isnull().sum()

title       0
year        0
revenue     0
imdb_id     0
tmdb_id     0
trakt_id    0
dtype: int64

In [ ]:
df.nunique()

title       10
year         3
revenue      9
imdb_id     10
tmdb_id     10
trakt_id    10
dtype: int64

In [ ]:
df.sample(5)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
909,Crime 101,2026,1100000,tt32430579,1171145,944042
774,GOAT,2026,4700000,tt27613895,1297842,1057839
970,Hoppers,2026,29000000,tt26443616,1327819,1085761
928,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
562,undertone,2026,9300000,tt35892608,1480387,1213506

In [ ]:
df.value_counts()

title                                                    year  revenue   imdb_id     tmdb_id  trakt_id
"Wuthering Heights"                                      2026  1700000   tt32897959  1316092  1077273     100
Crime 101                                                2026  1100000   tt32430579  1171145  944042      100
GOAT                                                     2026  4700000   tt27613895  1297842  1057839     100
Hoppers                                                  2026  29000000  tt26443616  1327819  1085761     100
Kiki's Delivery Service                                  1989  1700000   tt0097814   16859    10314       100
Reminders of Him                                         2026  18000000  tt33714084  1367642  1116720     100
Scream 7                                                 2026  8400000   tt27047903  1159559  934134      100
Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991  1500000   tt0103060   1497     991         100
The Bride!                                               2026  2100000   tt30851137  1159831  934595      100
undertone                                                2026  9300000   tt35892608  1480387  1213506     100
Name: count, dtype: int64